providers = ['...', 'python']
[phases.setup]
providers = ['...', 'python']
# Install dependencies for Python, Node.js, and Rust
aptPkgs = ['...', 'python3', 'nodejs', 'git', 'ffmpeg', 'imagemagick', 'file', 'python3-venv', 'python3-pip']


[phases.python-env]
# Set up and activate the Python virtual environment
cmds = [
  "python3 -m venv /myenv",
  ". /myenv/bin/activate",
  "pip install -r requirements.txt",
  "pip install torch==2.0.0 torchvision==0.15.0 torchaudio==2.0.0 --index-url https://download.pytorch.org/whl/cpu"
]

[phases.npm-install]
# Install Node.js dependencies with retries
cmds = [
  "npm config set fetch-retries 5",
  "npm config set fetch-retry-mintimeout 20000",
  "npm config set fetch-retry-maxtimeout 120000",
  "npm install"
]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmds = ["npm run start"]
dependsOn = ["build"]

